# Generated by Django 3.1.3 on 2020-12-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteboard',
            name='image_url',
            field=models.URLField(blank=True, max_length=350, verbose_name='Image link'),
        ),
    ]
